bill_coll/urls.py
from django.urls import path
from bill_coll import views
app_name = 'bill_coll'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('Dashboard', views.Dashboard, name = 'Dashboard'),
    path('admin_Dashboard', views.admin_Dashboard, name = 'admin_Dashboard'),
    path('consumer_Dashboard', views.consumer_Dashboard, name = 'consumer_Dashboard'),
    path('Users', views.Users, name = 'Users'),
    path('Collections', views.Collections, name = 'Collections'),
    path('Packages', views.Packages, name = 'Packages'),
    path('Home', views.Home, name = 'Home'),
    path('signup', views.signup, name = 'signup'),
    path('signin', views.signin, name = 'signin'),
    path('logout', views.logout, name = 'logout'),
    path('addpackage', views.addpackage, name = 'addpackage'),
    path('viewpackage/<int:package_id>/', views.viewpackage, name = 'viewpackage'),
    path('editpackage/<int:package_id>/', views.editpackage, name = 'editpackage'),
    path('deletepackage/<int:package_id>/', views.deletepackage, name = 'deletepackage'),
    path('addcity', views.addcity, name = 'addcity'),
    path('viewcity/<int:city_id>/', views.viewcity, name = 'viewcity'),
    path('editcity/<int:city_id>/', views.editcity, name = 'editcity'),
    path('deletecity/<int:city_id>/', views.deletecity, name = 'deletecity'),
    path('addarea', views.addarea, name = 'addarea'),
    path('viewarea/<int:area_id>/', views.viewarea, name = 'viewarea'),
    path('editarea/<int:area_id>/', views.editarea, name = 'editarea'),
    path('deletearea/<int:area_id>/', views.deletearea, name = 'deletearea'),
    path('addcollection', views.addcollection, name = 'addcollection'),
    path('viewcollection/<int:collection_id>/', views.viewcollection, name = 'viewcollection'),
    path('editcollection/<int:collection_id>/', views.editcollection, name = 'editcollection'),
    path('deletecollection/<int:collection_id>/', views.deletecollection, name = 'deletecollection'),
    path('user/<int:pk>/', views.update_profile, name='update_profile'),
    path('ajax/load-areas/', views.load_areas, name='ajax_load_areas'),
]

bill_coll_app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bill_coll.urls')),
]

urlpatterns = urlpatterns + \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bill_coll/models.py
from datetime import datetime

import django
from django.contrib.auth import get_user_model
from django.db import models
from django.utils import timezone

# Create your models here.
User = get_user_model()


class Month(models.Model):
    name = models.CharField(max_length=25)

    def __str__(self) -> str:
        return self.name


class City(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self) -> str:
        return self.name


class Area(models.Model):
    name = models.CharField(max_length=50)
    city = models.ForeignKey(City, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.name


class Package(models.Model):
    name = models.CharField(max_length=50)
    numberofchannels = models.IntegerField(default=0)
    numberofHDchannels = models.IntegerField(default=0)
    price = models.FloatField(default=0.0)

    def __str__(self) -> str:
        return self.name + "  ($" + str(self.price) + ")"


class Collection(models.Model):
    user_id = models.ForeignKey(
        User, on_delete=models.SET_NULL, blank=True, null=True)
    package = models.ForeignKey(Package, on_delete=models.SET_NULL, null=True)
    billDate = models.DateField(blank=True, null=True)
    billMonth = models.ForeignKey(
        Month, on_delete=models.CASCADE, null=True, blank=True)
    amount = models.FloatField(default=0.0)

    def __str__(self) -> str:
        return str(self.billMonth)


class Profile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    id_user = models.IntegerField()
    fullname = models.CharField(max_length=100, blank=True, null=True)
    photo = models.ImageField(
        upload_to='bill_coll_images', default='placeholderimg.jpg')
    package = models.ForeignKey(Package, on_delete=models.SET_NULL, null=True)
    address = models.CharField(max_length=100)
    area = models.ForeignKey(
        Area, on_delete=models.SET_NULL, blank=True, null=True)
    city = models.ForeignKey(
        City, on_delete=models.SET_NULL, blank=True, null=True)
    paidThruMonth = models.CharField(max_length=50, null=True, blank=True)

    def __str__(self) -> str:
        return self.fullname

bill_coll/forms.py
from fileinput import FileInput

from django import forms

from bill_coll import models


class CityForm(forms.ModelForm):
    class Meta:
        model = models.City
        fields = "__all__"
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
        }


class AreaForm(forms.ModelForm):
    class Meta:
        model = models.Area
        fields = "__all__"
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'city': forms.Select(attrs={'class': 'form-control'}),
        }


class PackageForm(forms.ModelForm):
    class Meta:
        model = models.Package
        fields = "__all__"
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'numberofchannels': forms.TextInput(attrs={'class': 'form-control'}),
            'numberofHDchannels': forms.TextInput(attrs={'class': 'form-control'}),
            'price': forms.TextInput(attrs={'class': 'form-control'})
        }


class CollectionForm(forms.ModelForm):
    class Meta:
        model = models.Collection
        fields = ['user_id', 'package', 'billMonth', 'amount', 'billDate']
        widgets = {
            'user_id': forms.Select(attrs={'class': 'form-control'}),
            'package': forms.Select(attrs={'class': 'form-control'}),
            'billMonth': forms.Select(attrs={'class': 'form-control'}),
            'amount': forms.TextInput(attrs={'class': 'form-control'}),
            'billDate': forms.DateInput(attrs={'class': 'form-control'}),
        }

        labels = {
            'user_id': 'User',
            'package': 'Package',
            'billMonth': 'Bill Month',
            'amount': 'Bill Amount',
            'billDate': 'Bill Date (yyyy-mm-dd)'
        }


class UpdateProfile(forms.ModelForm):
    class Meta:
        model = models.Profile
        # fields = "__all__"
        fields = ['fullname', 'photo', 'city', 'area', 'package', 'address']
        widgets = {
            'address': forms.TextInput(attrs={'class': 'form-control'}),
            'package': forms.Select(attrs={'class': 'form-control'}),
            'city': forms.Select(attrs={'class': 'form-control'}),
            'area': forms.Select(attrs={'class': 'form-control'}),
            'photo': forms.FileInput(attrs={'class': 'form-control'}),
            'fullname': forms.TextInput(attrs={'class': 'form-control'}),
        }

        labels = {
            'photo': 'Select a new photo'
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['area'].queryset = models.Area.objects.none()
        if 'city' in self.data:
            try:
                city_id = int(self.data.get('city'))
                self.fields['area'].queryset = models.Area.objects.filter(
                    city_id=city_id).order_by('name')

            except (ValueError, TypeError):
                pass
        elif self.instance.pk:
            self.fields['area'].queryset = self.instance.city.area_set.order_by(
                'name')

bill_coll/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group, User, auth
from django.shortcuts import get_object_or_404, redirect, render

from bill_coll import forms
from bill_coll.decorators import *

from .ExtraneousFolder import ExtraFunctions
from .models import *

# Create your views here.

# @login_required(login_url='/signin')


def index(request):
    isAdmin = False
    user = request.user
    print("userrrid", user.id)
    print(request.user.pk)
    group = None
    if request.user.groups.exists():
        group = request.user.groups.all()[0].name
    if (group == "consumer"):
        return redirect("/consumer_Dashboard")
    if (group == "admin"):
        # isAdmin = True
        return redirect("/admin_Dashboard")
    else:
        print("home sweet home")
        return redirect("/Home")
    # user = Profile.objects.get(id_user=request.user.id)
    collection_list = Collection.objects.order_by('package')
    print(collection_list)
    package_list = Package.objects.order_by('name')
    dict = {'title': "homepage", 'collection_list': collection_list,
            'package_list': package_list, 'user': user}
    # return render(request, 'bill_coll/index.html', context=dict)


@login_required(login_url='/signin')
def Dashboard(request):
    user = request.user
    group = None
    if request.user.groups.exists():
        group = request.user.groups.all()[0].name
    if (group == "consumer"):
        return redirect("/consumer_Dashboard")
    if (group == "admin"):
        return redirect("/admin_Dashboard")
    return redirect("/")


@allowed_user(allowed_roles=['admin'])
@login_required(login_url='/signin')
def admin_Dashboard(request):
    group = None
    if request.user.groups.exists():
        group = request.user.groups.all()[0].name
    isAdmin = ExtraFunctions.isAdmin(group)
    user = request.user
    collection_list = Collection.objects.order_by('billDate')[::-1]
    package_list = Package.objects.order_by('name')
    dict = {'title': "Dashboard", 'collection_list': collection_list,
            'user': user, 'user_id': request.user.pk, 'isAdmin': isAdmin}
    return render(request, 'bill_coll/admin_Dashboard.html', context=dict)


@allowed_user(allowed_roles=['consumer'])
@login_required(login_url='/signin')
def consumer_Dashboard(request):
    user = request.user
    user_profile = Profile.objects.get(id_user=user.pk)
    print(user_profile.photo.url)
    print(user.id)
    dict = {
        'title': "Dashboard",
        'user': user,
        'profile': user_profile
    }
    return render(request, 'bill_coll/consumer_Dashboard.html', context=dict)


def Home(request):
    # user = Profile.objects.filter(id_user=request.user.pk).first()
    group = None
    if request.user.groups.exists():
        group = request.user.groups.all()[0].name
    isAdmin = ExtraFunctions.isAdmin(group)
    user = request.user
    print("user in home page", user)
    package_list = Package.objects.order_by('name')
    dict = {'title': "Homepage", 'package_list': package_list, 'user': user, 'isAdmin': isAdmin}
    return render(request, 'bill_coll/Home.html', context=dict)


@allowed_user(allowed_roles=['admin'])
@login_required(login_url='/signin')
def Collections(request):
    # isAdmin = False
    group = None
    if request.user.groups.exists():
        group = request.user.groups.all()[0].name
    if (group == "admin"):
        isAdmin = request.user.groups.exists()
        # return redirect("/admin_Dashboard")
    user = request.user
    print("hello", user)
    # print("pk is", pk)
    # user = get_object_or_404(User,username=pk)
    print("user is", request.user.pk)
    collection_list = Collection.objects.order_by('package')
    package_list = Package.objects.order_by('name')
    dict = {'title': "Dashboard", 'collection_list': collection_list,
            'user': user, 'user_id': request.user.pk, 'isAdmin': isAdmin}
    return render(request, 'bill_coll/Collection.html', context=dict)


@allowed_user(allowed_roles=['admin'])
@login_required(login_url='/signin')
def Packages(request):  # , package_id):
    user = User.objects.filter(pk=request.user.pk).first()
    group = None
    if request.user.groups.exists():
        group = request.user.groups.all()[0].name
    isAdmin = ExtraFunctions.isAdmin(group)
    # package_list = Package.objects.filter(pk=package_id)
    package_list = Package.objects.order_by('name')
    dict = {'title': "homepage", 'package_list': package_list,
            'user': user, 'isAdmin': isAdmin}
    return render(request, 'bill_coll/Packages.html', context=dict)


@allowed_user(allowed_roles=['admin'])
@login_required(login_url='/signin')
def Users(request):
    dict = {'title': "Users"}
    return render(request, 'bill_coll/Users.html', context=dict)

# @unauthenticated_user


def signup(request):
    user = Profile.objects.filter(
        id_user=request.user.id).first()  # prevents anonymous user
    dict = {'user': user}
    if request.user.is_authenticated: #is_authenticated will return true/false
        return redirect('/')
    else:
        if request.method == 'POST':
            username = request.POST['username']
            email = request.POST['email']
            password = request.POST['password']
            password2 = request.POST['password2']
            if password == password2:
                if User.objects.filter(email=email).exists():
                    messages.info(request, 'Email already exists.')
                    return redirect('/signup')
                if User.objects.filter(username=username).exists():
                    messages.info(request, 'Username is already taken.')
                    return redirect('/signup')
                else:
                    user = User.objects.create_user(
                        username=username, email=email, password=password)
                    user.save()
                    # create a profile for new user
                    user_model = User.objects.get(username=username)
                    group = Group.objects.get(name='consumer')
                    user_model.groups.add(group)
                    new_profile = Profile.objects.create(
                        user=user_model, id_user=user_model.id)
                    print(user_model)
                    print("id_user exists?", new_profile.id_user)
                    new_profile.save()
                    messages.success(request, 'Signup Successful')
                    return redirect('/signup')

            else:
                messages.info(request, 'Password didn\'t match.')
                return redirect('/signup')

    return render(request, 'bill_coll/signup.html', context=dict)

# @unauthenticated_user


def signin(request):
    # user = request.user #this will work after sign in
    user = Profile.objects.filter(id_user=request.user.pk).first()
    dict = {'user': user}
    # print("username", user.user.username)
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        # null if it can't find
        user = auth.authenticate(username=username, password=password)

        if user is not None:
            auth.login(request, user)
            return redirect('/')
        else:
            messages.info(request, 'Credentials Invalid')
            return redirect('/signin')

    else:
        return render(request, 'bill_coll/signin.html', context=dict)


def logout(request):
    auth.logout(request)
    return redirect('/signin')


def addpackage(request):
    form = forms.PackageForm
    if request.method == "POST":  # if user typed something, Post == data hidden
        form = forms.PackageForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return index(request)

    dict = {'title': "addpackage", 'package_form': form}
    return render(request, 'bill_coll/addpackage.html', context=dict)


def viewpackage(request, package_id):
    user = request.user
    package_info = Package.objects.get(pk=package_id)  # pk is primary key
    dict = {'title': "viewpackage", 'package_info': package_info, 'user': user}
    return render(request, 'bill_coll/viewpackage.html', context=dict)


def editpackage(request, package_id):
    edit_package = Package.objects.get(pk=package_id)
    form = forms.PackageForm(instance=edit_package)
    user = Profile.objects.filter(id_user=request.user.pk)
    if request.method == "POST":  # if user typed something, Post == data hidden
        form = forms.PackageForm(request.POST, instance=edit_package)

        if form.is_valid():
            form.save(commit=True)
            # return index(request)
            return redirect('/Packages')

    dict = {'title': "editpackage", 'edit_package_form': form, 'user': user}
    return render(request, 'bill_coll/editpackage.html', context=dict)


def deletepackage(request, package_id):
    package_info = Package.objects.get(pk=package_id)
    package_info.delete()
    dict = {'title': "deletepackage"}
    return render(request, 'bill_coll/deletepackage.html', context=dict)


def addcity(request):
    form = forms.CityForm
    if request.method == "POST":  # if user typed something, Post == data hidden
        form = forms.CityForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return index(request)

    dict = {'title': "addcity", 'city_form': form}
    return render(request, 'bill_coll/addcity.html', context=dict)


def viewcity(request, city_id):
    user = request.user
    city_info = City.objects.get(pk=city_id)  # pk is primary key
    dict = {'title': "viewcity", 'city_info': city_info, 'user': user}
    return render(request, 'bill_coll/viewcity.html', context=dict)


def editcity(request, city_id):
    edit_city = City.objects.get(pk=city_id)
    form = forms.CityForm(instance=edit_city)

templates/bill_coll/Users.html
{% extends 'bill_coll/base.html' %} {% block body_block %}
<div class="container mt-3">
    <div class="row">
        <div class="col">
            <h1>"{{title}}"</h1>
        </div>
    </div>
</div>
{% endblock %}

templates/bill_coll/addarea.html
{% extends 'bill_coll/base.html' %} {% block body_block %}

<div class="container mt-3">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <div class="card">
                <div class="card-header">
                    <h2>Add Area</h2>
                        </div>
                <div class="card-body">
                        <div>
                            <form action="" method="POST" enctype="multipart/form-data">
                                {{area_form.as_p}} {% csrf_token %}
                                <input class="btn btn-primary mt-2" type="submit" value="Add Area" />
                            </form>
                        </div>
                </div>
                </div>
            </div>
        </div>
</div>

{% endblock %}

templates/bill_coll/addcity.html
{% extends 'bill_coll/base.html' %} {% block body_block %}

<div class="container mt-3">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <div class="card">
                <div class="card-header">
                    <h2>Add City</h2>
                        </div>
                <div class="card-body">
                        <div>
                            <form action="" method="POST" enctype="multipart/form-data">
                                {{city_form.as_p}} {% csrf_token %}
                                <input class="btn btn-primary mt-2" type="submit" value="Add City" />
                            </form>
                        </div>
                </div>
                </div>
            </div>
        </div>
</div>

{% endblock %}

templates/bill_coll/addcollection.html
{% extends 'bill_coll/base.html' %} {% block body_block %}

<div class="container mt-3">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <div class="card rounded-0 border-info">
        <div
          class="card-header bg-info d-flex align-items-center rounded-0 text-white"
        >
          <h4>Add Collection</h4>
        </div>
        <div class="card-body">
          <div>
            <form action="" method="POST" enctype="multipart/form-data">
              {{collection_form.as_p}} {% csrf_token %}

              <input
                class="btn btn-primary mt-2"
                type="submit"
                value="Add Collection"
              />
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

templates/bill_coll/admin_Dashboard.html
{% extends 'bill_coll/base.html' %} {% block body_block %}

<div class="container mt-3">
  <div class="row">
    <div class="col">
      <h2 class="text-success text-center text-uppercase mb-5">
        Welcome to Admin Dashboard!
      </h2>
      <div class="card rounded-0">
        <div
          class="card-header d-flex align-items-center bg-info text-white rounded-0"
        >
          <h4>Bill Collection List</h4>

          <a
            class="btn btn-primary ms-auto rounded-0"
            href="{% url 'bill_coll:addcollection' %}"
            >Add Collection</a
          >
        </div>
        <div class="card-body">
          <table class="table table-bordered mt-3">
            <thead class="table-dark">
              <tr>
                <th scope="col">User ID</th>
                <th scope="col">User Package</th>
                <th scope="col">Collection Date</th>
                <th scope="col">Bill Month</th>
                <th scope="col">Bill Amount</th>
                <th scope="col">Actions</th>
              </tr>
            </thead>
            <tbody>
              {% for collection in collection_list %}
              <tr>
                <td>{{collection.user_id}}</td>
                <td>{{collection.package}}</td>
                <td>{{collection.billDate}}</td>
                <td>{{collection.billMonth}}</td>
                <td>${{collection.amount}}</td>
                <td>
                  <a
                    class="btn btn-sm rounded-0 btn-info"
                    href="{% url 'bill_coll:viewcollection' collection_id=collection.id %}"
                    >View</a
                  >
                  <a
                    class="btn btn-sm rounded-0 btn-warning"
                    href="{% url 'bill_coll:editcollection' collection_id=collection.id %}"
                    >Edit</a
                  >
                  <a
                    class="btn btn-sm rounded-0 btn-danger"
                    href="{% url 'bill_coll:deletecollection' collection_id=collection.id %}"
                    >Delete</a
                  >
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/bill_coll/base.html
{%load static%}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0"
    />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />

    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
    />

    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
    />

    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.10.0/css/bootstrap-datepicker.min.css"
    />

    <link href="/static/css/style.css?{% now 'U' %}" rel="stylesheet" />
    <title>"{{title}}"</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <a class="navbar-brand">LOGO</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto ms-5 mb-2 mb-lg-0">
            {% if user %}
            <li class="nav-item">
              <a
                class="nav-link {% if request.path == '/admin_Dashboard' or request.path == '/consumer_Dashboard' %}active{% endif %}"
                aria-current="page"
                href="{% url 'bill_coll:Dashboard' %}"
                >Dashboard
              </a>
            </li>
            {% endif %}
            <li class="nav-item">
              <a
                class="nav-link {% if request.path == '/Home' %}active{% endif %}"
                aria-current="page"
                href="{% url 'bill_coll:Home' %}"
                >Home</a
              >
            </li>
            {% if isAdmin %}
            <li class="nav-item">
              <a
                class="nav-link {% if request.path == '/Packages' %}active{% endif %}"
                href="{% url 'bill_coll:Packages' %}"
                >Packages</a
              >
            </li>
            <li class="nav-item">
              <a
                class="nav-link {% if request.path == '/Users' %}active{% endif %}"
                href="{% url 'bill_coll:Users' %}"
                >Users</a
              >
            </li>
            <li class="nav-item">
              <a
                class="nav-link {% if request.path == '/Collections' %}active{% endif %}"
                href="{% url 'bill_coll:Collections' %}"
                >Collection</a
              >
            </li>
            {% endif %}
          </ul>
          <ul class="navbar-nav">
            {% if not user %}
            <a class="nav-link" href="{% url 'bill_coll:signin' %}">Log in</a>
            <a class="nav-link" href="{% url 'bill_coll:signup' %}">Sign up</a>
            {% endif %} {% if user %}
            <a class="nav-link" href="{% url 'bill_coll:logout' %}">Log out</a>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
    {% block body_block %} {% endblock %}

    <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.10.0/js/bootstrap-datepicker.min.js"></script>
    <script src="/static/js/app.js"></script>
  </body>
</html>

templates/bill_coll/deletecollection.html
{% extends 'bill_coll/base.html' %} {% block body_block %}
<div class="container mt-3">
    <div class="row">
      <div class="col"><h2> Collection deleted successfully</h2></div>
      </div>
</div>



{% endblock %}

templates/bill_coll/editarea.html
{% extends 'bill_coll/base.html' %} {% block body_block %}
<div class="container mt-3">
    <div class="row">
        <div class="col">
            <h1>"{{title}}"</h1>
            <div>
                <form action="" method="POST">
                    {{edit_area_form.as_p}} {% csrf_token %} <!-- csrf token is used to prevent spamming -->

                    <input class="btn btn-primary" type="submit" value="Edit Area"/>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/bill_coll/index.html
{% extends 'bill_coll/base.html' %} {% block body_block %}
<div class="container mt-3">
    <div class="row">
        <div class="col">
            <h1>collectionlist</h1>
            {% if collection_list %}
            <table class="table">
                <thead>
                <tr>
                    <th scope="col">package</th>
                    <th scope="col">billMonth</th>
                    <th scope="col">Amount</th>
                </tr>
                </thead>
                <tbody>
                <!--   {% for food in food_list %} -->
                {% for collection in collection_list %}
                <tr>
                    <td>{{collection.package}}</td> <!-- <td>{{collection.package.name}}</td>-->
                    <td>{{collection.billMonth}}</td>
                    <td>{{collection.Amount}}</td>
                    <td>
                        <a class="btn btn-primary"
                           href="{% url 'bill_coll:viewcollection' collection_id=collection.id %}">View</a>
                        <a class="btn btn-primary"
                           href="{% url 'bill_coll:editcollection' collection_id=collection.id %}">Edit</a>
                    </td>
                </tr>
                {% endfor %}
                <!-- {% endfor %} -->
                </tbody>
            </table>
            {% else %}
            <h2>no collection available</h2>
            {% endif %}
            <!-- <h2>packagelist</h2>
                        {% if package_list %}
            <table class="table">
              <thead>
                <tr>
                    <th scope="col">Name</th>
                    <th scope="col">Number of Channels</th>
                    <th scope="col">Number of HD Channels</th>
                    <th scope="col">Price</th>
                </tr>
              </thead>
              <tbody>
              {% for package in package_list %}
              <tr>
                  <td>{{package.name}}</td>
                  <td>{{package.numberofchannels}}</td>
                  <td>{{package.numberofHDchannels}}</td>
                  <td>{{package.price}}</td>
                  <td>
                      <a class="btn btn-primary" href="{% url 'bill_coll:viewpackage' package_id=package.id %}">View</a>
                      <a class="btn btn-secondary" href="{% url 'bill_coll:editpackage' package_id=package.id %}">Edit</a>
                      <a class="btn btn-danger" href="{% url 'bill_coll:deletepackage' package_id=package.id %}">Delete</a>
                  </td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
                        {% else %}
                        <h2>no package available</h2>
                        {% endif %} -->
        </div>
    </div>
</div>
{% endblock %}

templates/bill_coll/update_profile.html
{% extends 'bill_coll/base.html' %} {% block body_block %}
<div class="container mt-3">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <div class="card mb-5 rounded-0 border-info">
        <div
          class="card-header d-flex align-items-center rounded-0 bg-info text-white"
        >
          <h4>Update Profile</h4>
        </div>
        <div class="card-body">
          <div>
            {% for message in messages %}
            <h5 class="text-danger">{{message}}</h5>
            {% endfor %}

            <div class="my=3">
              <img
                class="img-thumbnail mb-3"
                style="width: 100px"
                src="{{user.photo.url}}"
                alt="{{user.user.username}}"
              />
            </div>

            <form
              action=""
              method="POST"
              enctype="multipart/form-data"
              id="update-form"
              data-areas-url="{% url 'bill_coll:ajax_load_areas' %}"
            >
              <!-- # for id, . for class-->
              {% csrf_token %} {{form.as_p}}
              <input
                class="btn btn-primary"
                type="submit"
                value="Update Profile"
              />
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}